.SH "NAME"
tap \- the snappy music player
.SH "SYNOPSIS"
.B tap
.RB [ \-asdphV ] [PATH]
.br
.SH "DESCRIPTION"
.B tap
is an audio player for the terminal with fuzzy-finder.
.br
.SH "SEE ALSO"
.BR fzy,
.br
.SH "OPTIONS"
.sp
\-a, \-\-automate
.RS 4
Runs an automated player without the TUI.
.RE
.sp
\-s, \-\-set-default
.RS 4
Sets a default directory using the provided path.
.RE
.sp
\-d, \-\-default
.RS 4
Runs tap with the default directory, if set.
.RE
.sp
\-p, \-\-print
.RS 4
default  Prints the default directory, if set.
.RE
.sp
\-h, \-\-help
.RS 4
Print help.
.RE
.sp
\-V, \-\-version
.RS 4
Print version.
.SH "BUGS"
Please file bugs on the Github page.
.SH "AUTHORS"
.B tap
was developed by Tim Dubbins.
.br
.SH "COPYRIGHT"
Copyright \(co 2023 Tim Dubbins (MIT)
.LP
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
