.SH "NAME"
tap \- TUI audio player
.SH "SYNOPSIS"
.B tap
.RB [ \-asdphV ] [PATH]
.br
.SH "DESCRIPTION"
.B tap
is a lightweight audio player for the terminal with fuzzy-finder.
.br
.SH "OPTIONS"
.sp
\-a, \-\-automate
.RS 4
Run an automated player without the TUI.
.RE
.sp
\-s, \-\-set-default
.RS 4
Set a default directory using the provided path.
.RE
.sp
\-d, \-\-default
.RS 4
Run tap with the default directory, if set.
.RE
.sp
\-p, \-\-print
.RS 4
default  Prints the default directory, if set.
.RE
.sp
\-h, \-\-help
.RS 4
Print help.
.RE
.sp
\-V, \-\-version
.RS 4
Print version.
.SH "BUGS"
Bugs can be reported on Github: https://github.com/timdubbins/tap/issues
